[build]
builder = "nixpacks"

[deploy]
startCommand = "cd urban-explore/pois-manager && uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10